export const routes = {
  PROFILENAVIGATOR: 'ProfileNavigator',
  WALLETNAVIGATOR: 'WalletNavigator',
  MAPNAVIGATOR: 'MapNavigator',
  LISTNAVIGATOR: 'ListNavigator',
  LIKEDNAVIGATOR: 'LikedNavigator',
  NOTIFYNAVIGATOR: 'NotifyNavigator',

  MAP: 'MapScreen',
  LIST: 'ListScreen',
  ABOUT: 'AboutScreen',
  REVIEW: 'ReviewScreen',
  LIKED: 'LikedScreen',
  PROFILE: 'ProfileScreen',
  LOGIN: 'LoginScreen',
  LOGOUT: 'Logout',
  REGISTER: 'RegisterScreen',
  SPLASH: 'SplashScreen',
  WALLET: 'WalletScreen',
  SCANPAY: 'ScanPayScreen',
  MANUALPAY: 'ManualPayScreen',
  CONFIRMPAY: 'ConfirmPayScreen',
  SCANREQUEST: 'ScanRequestScreen',
  MANUALREQUEST: 'ManualRequestScreen',
  CONFIRMREQUEST: 'ConfirmRequestScreen',
  NOTIFY: 'NotifyScreen',
  NOTIFYSETTING: 'NotifySettingScreen',
  FILTER: 'FilterScreen',

  HISTORY: 'HistoryScreen',
  REVIEWS: 'ReviewsScreen',
  COMMENTS: 'CommentsScreen',
  FOLLOWING: 'FollowingScreen',
  HELP: 'HelpScreen',
  CONTACT: 'ContactScreen',
  ABOUTS: 'AboutsScreen',

  NOTFOUND: 'NotFoundScreen',
};
