export const Place = [
  {
    id: 1,
    longitude: -71.08,
    latitude: 42.387,
    name: 'Super Employer',
    time: '8:00 AM - 8:00 PM',
    cover: require('../assets/images/logo2.png'),
    totalRating: 4.6,
    totalReview: 12,
    isRecreational: true,
    isMedical: true,
    serviceStatus: 'Open',
    address: 'Słoneczna 27, 55-010 Radwanice',
    distance: '8,1 Miles Away',
    isFavourite: false,
  },
  {
    id: 2,
    longitude: -71.58,
    latitude: 43.387,
    name: 'Growing',
    time: '8:00 AM - 8:00 PM',
    cover: require('../assets/images/LOGO.png'),
    totalRating: 4.6,
    totalReview: 12,
    isRecreational: true,
    isMedical: true,
    serviceStatus: 'Open',
    address: 'Słoneczna 27, 55-010 Radwanice',
    distance: '8,1 Miles Away',
    isFavourite: false,
  },
  {
    id: 3,
    longitude: -72.11,
    latitude: 41.687,
    name: 'Funky Baba',
    time: '8:00 AM - 8:00 PM',
    cover: require('../assets/images/LOGOboy.png'),
    totalRating: 3.6,
    totalReview: 3,
    isRecreational: true,
    isMedical: true,
    serviceStatus: 'Closed',
    address: 'Słoneczna 27, 55-010 Radwanice',
    distance: '8,1 Miles Away',
    isFavourite: false,
  },
];
