export const Stores = [
  {
    id: 1,
    longitude: -71.08,
    latitude: 42.387,
    name: 'Super Employer',
    cover: require('../assets/images/logo2.png'),
    time: '8:00 AM - 8:00 PM',
    totalRating: 4.6,
    totalReview: 12,
    serviceStatus: 'Open',
    isRecreational: true,
    isMedical: true,
    address: 'Słoneczna 27, 55-010 Radwanice',
    distance: '8,1 Miles Away',
    isFavourite: false,
  },
  {
    id: 2,
    longitude: -71.58,
    latitude: 43.387,
    name: 'Growing',
    cover: require('../assets/images/LOGO.png'),
    time: '8:00 AM - 8:00 PM',
    totalRating: 4.6,
    totalReview: 12,
    serviceStatus: 'Open',
    isRecreational: true,
    isMedical: true,
    address: 'Słoneczna 27, 55-010 Radwanice',
    distance: '8,1 Miles Away',
    isFavourite: true,
  },
  {
    id: 3,
    longitude: -72.11,
    latitude: 41.687,
    name: 'Funky Baba',
    cover: require('../assets/images/LOGOboy.png'),
    time: '8:00 AM - 8:00 PM',
    totalRating: 3.6,
    totalReview: 3,
    serviceStatus: 'Closed',
    isRecreational: true,
    isMedical: true,
    address: 'Słoneczna 27, 55-010 Radwanice',
    distance: '8,1 Miles Away',
    isFavourite: false,
  },
  {
    id: 4,
    longitude: -73.08,
    latitude: 43.387,
    name: 'Best Assist',
    cover: require('../assets/images/logo2.png'),
    time: '8:00 AM - 8:00 PM',
    totalRating: 4.1,
    totalReview: 6,
    serviceStatus: 'Open',
    isRecreational: true,
    isMedical: true,
    address: 'Słoneczna 27, 55-010 Radwanice',
    distance: '8,1 Miles Away',
    isFavourite: false,
  },
  {
    id: 5,
    longitude: -74.58,
    latitude: 44.387,
    name: 'Hello World',
    cover: require('../assets/images/logo2.png'),
    time: '8:00 AM - 8:00 PM',
    totalRating: 4.6,
    totalReview: 15,
    serviceStatus: 'Closed',
    isRecreational: true,
    isMedical: true,
    address: 'Słoneczna 27, 55-010 Radwanice',
    distance: '8,1 Miles Away',
    isFavourite: true,
  },
  {
    id: 6,
    longitude: -75.11,
    latitude: 45.687,
    name: 'Review Liked',
    cover: require('../assets/images/logo2.png'),
    time: '8:00 AM - 8:00 PM',
    totalRating: 3.3,
    totalReview: 89,
    serviceStatus: 'Closed',
    isRecreational: true,
    isMedical: true,
    address: 'Słoneczna 27, 55-010 Radwanice',
    distance: '8,1 Miles Away',
    isFavourite: true,
  },
];
